metadata:
  id: conllu-import-test
  name:
    eng: CoNLL-U import test corpora
    swe: ""
  language: est
  description:
    eng: |+
      Copied from https://github.com/UniversalDependencies/tools/blob/master/example-data/long-token-to-text.conllu
    swe: |2+

classes:
  sentence: sentence
import:
  # source_dir: source
  importer: sbx_conllu:parse
  # text_annotation: text

sbx_conllu:
  elements:
    - text
    - sentence

export:
  default:
    # - conll_export:conllu
    - csv_export:csv
    - xml_export:pretty
    - xml_export:preserved_format
  annotations:
    # - <sentence>:misc.id
    - <token>:misc.word
    - <text>:readability.lix
# dateformat:
#   datetime_from: date
#   datetime_informat: ""
