metadata:
  id: conllu-import-test
  name:
    eng: CoNLL-U import test corpora
    swe: ""
  language: eng
  description:
    eng: |+
      Copied from https://github.com/UniversalDependencies/UD_English-EWT/blob/master/en_ewt-ud-test.conllu

classes:
  sentence: sentence
  token: token
  "token:pos": token:xpos
import:
  # source_dir: source
  importer: sbx_conllu:parse
  # text_annotation: text

sbx_conllu:
  import_attributes:
    - text
    - sentence
    - token
    - token:xpos

export:
  default:
    # - conll_export:conllu
    - csv_export:csv
    - xml_export:pretty
    - xml_export:preserved_format
  annotations:
    # - <sentence>:misc.id
    - <token>:misc.word
    - <text>:readability.lix
