metadata:
  id: conllu-import-test
  name:
    eng: CoNLL-U import test corpora
    swe: ""
  language: eng
  description:
    eng: |+
      Copied from https://universaldependencies.org/format.html#sentence-boundaries-and-comments

classes:
  sentence: sentence
  token: token
  # "token:pos": token:xpos
import:
  # source_dir: source
  importer: sbx_conllu:parse
  # text_annotation: text

sbx_conllu:
  import_attributes:
    - token:xpos

export:
  default:
    - csv_export:csv
    - xml_export:pretty
    - xml_export:preserved_format
  annotations:
    # - <sentence>:misc.id
    - <token>:misc.word
